# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='favorited_by',
            new_name='favorited',
        ),
    ]
